### PR TITLE
display: Solve problem with debug message in OTA

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Review by rafaellehmkuhl — APPROVED** [review]
I dont remember to see this bug. How the progress variable was appearing?

**Comment by patrickelectric** [comment]
It was 'OTA: Progress: %.1f' or something with the .1f and not the real number.

**Comment by rafaellehmkuhl** [comment]
Right

**Review by Williangalvani — APPROVED** [review]
Why didn't it work before?
nevermind, just read the comments above.

**Pull request merged**
